# Generated by Django 3.2 on 2021-05-15 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ridit', '0002_auto_20210514_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='school',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ridit.gender'),
        ),
    ]
