# Generated by Django 3.2 on 2021-05-15 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ridit', '0003_auto_20210515_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='gender',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
