# Generated by Django 3.2 on 2021-05-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridit', '0007_auto_20210516_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='days',
            field=models.CharField(choices=[('0', '7 days'), ('1', '15 days')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='gender',
            field=models.CharField(choices=[('0', 'Male'), ('1', 'Female')], max_length=10),
        ),
    ]
