# Generated by Django 3.2 on 2021-05-21 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ridit', '0008_auto_20210521_1333'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
