# Generated by Django 3.2 on 2021-05-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridit', '0010_partner_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='query',
            field=models.CharField(max_length=300),
        ),
    ]
