# Generated by Django 3.2 on 2021-05-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridit', '0011_alter_partner_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='query',
            field=models.TextField(max_length=300),
        ),
    ]
