# Generated by Django 3.2 on 2021-05-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridit', '0012_alter_partner_query'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='service',
        ),
        migrations.AddField(
            model_name='partner',
            name='service',
            field=models.ManyToManyField(to='ridit.Service'),
        ),
    ]
