# Generated by Django 3.2 on 2021-05-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridit', '0015_chauffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chauffer',
            name='days',
            field=models.CharField(max_length=2),
        ),
    ]
