# Generated by Django 3.2 on 2021-05-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridit', '0017_puc'),
    ]

    operations = [
        migrations.AddField(
            model_name='chauffer',
            name='price',
            field=models.IntegerField(default=499),
            preserve_default=False,
        ),
    ]
