# Generated by Django 3.2 on 2021-05-26 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridit', '0018_chauffer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='puc',
            name='price',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puc',
            name='vehicle_type',
            field=models.CharField(choices=[('2w', '2 wheeler'), ('3w', '3 wheeler'), ('4w', '4 wheeler'), ('4cw', '4C Wheeler'), ('hw', 'Heavy Wheeler')], default='hw', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chauffer',
            name='days',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
