# Generated by Django 3.2 on 2021-05-26 11:38

from django.db import migrations, models
import ridit.models


class Migration(migrations.Migration):

    dependencies = [
        ('ridit', '0020_alter_chauffer_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chauffer',
            name='days',
            field=models.IntegerField(validators=[ridit.models.validate_range]),
        ),
    ]
