# Generated by Django 3.2 on 2021-05-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridit', '0021_alter_chauffer_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puc',
            name='vehicle_type',
            field=models.CharField(choices=[('2w', '2 wheeler'), ('3w', '3 wheeler'), ('4w', '4 wheeler'), ('4cw', '4 Wheeler Commercials'), ('hw', 'Heavy Wheeler')], max_length=20),
        ),
        migrations.AlterField(
            model_name='school',
            name='vehicle',
            field=models.CharField(choices=[('0', 'Two Wheeler'), ('1', 'Four Wheeler')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
