# Generated by Django 3.2 on 2021-05-28 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridit', '0023_auto_20210528_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='email',
            field=models.EmailField(max_length=200, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
