# Generated by Django 3.2 on 2021-05-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridit', '0025_alter_school_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
