# Generated by Django 3.2 on 2021-05-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridit', '0027_alter_school_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='uuid',
            field=models.CharField(default='a', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
