# Generated by Django 3.2.3 on 2021-05-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridit', '0027_alter_school_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField(max_length=500)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
    ]
