# Generated by Django 3.2 on 2021-05-30 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ridit', '0028_school_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='uuid',
        ),
    ]
