# Generated by Django 3.2 on 2021-06-04 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ridit', '0028_contact'),
        ('ridit', '0029_remove_school_uuid'),
    ]

    operations = [
    ]
