# Generated by Django 3.2 on 2021-06-04 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ridit', '0030_merge_0028_contact_0029_remove_school_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ridit.city'),
        ),
    ]
