# Generated by Django 3.2.3 on 2021-06-17 10:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ridit', '0031_alter_partner_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be of 10 digits', regex='^\\+?1?\\d{10}$')]),
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be of 10 digits', regex='^\\+?1?\\d{10}$')])),
                ('exp_date', models.DateField()),
                ('ins_type', models.CharField(choices=[('li', 'Life Insurance'), ('mi', 'Motor Insurance'), ('hi', 'Health Insurance'), ('ti', 'Travel Insurance'), ('pi', 'Property Insurance'), ('mo', 'Mobile Insurance'), ('ci', 'Cycle Insurance'), ('bi', 'Bite-size Insurance')], max_length=30)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ridit.city')),
            ],
        ),
    ]
