# Generated by Django 3.2.3 on 2021-06-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridit', '0032_auto_20210617_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='vehicle',
            field=models.CharField(choices=[('2w', '2 wheeler'), ('3w', '3 wheeler'), ('4w', '4 wheeler')], max_length=20),
        ),
    ]
