# Generated by Django 3.2.3 on 2021-06-26 05:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridit', '0034_auto_20210621_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chauffer',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Only Alphabets and spaces are allowed', regex='^[A-Za-z\\s]*$')]),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Only Alphabets and spaces are allowed', regex='^[A-Za-z\\s]*$')]),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Only Alphabets and spaces are allowed', regex='^[A-Za-z\\s]*$')]),
        ),
        migrations.AlterField(
            model_name='puc',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Only Alphabets and spaces are allowed', regex='^[A-Za-z\\s]*$')]),
        ),
        migrations.AlterField(
            model_name='rto',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Only Alphabets and spaces are allowed', regex='^[A-Za-z\\s]*$')]),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Only Alphabets and spaces are allowed', regex='^[A-Za-z\\s]*$')]),
        ),
    ]
