# Generated by Django 3.2.3 on 2021-06-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridit', '0035_auto_20210626_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puc',
            name='vehicle_no',
            field=models.CharField(max_length=10),
        ),
    ]
